### ISSUE TITLE
Import old releases as branches

### ISSUE THREAD

**Issue by camillobruni** [WebKit/JetStream#3]
It would be nice to import all the old jetstream releases as separate branches for documenting purposes.

| Branch Name  | Source | 
| -- | -- |
| v1.1 | https://github.com/WebKit/WebKit/tree/main/Websites/browserbench.org/JetStream1.1 | 
| v2.0 | https://github.com/WebKit/WebKit/tree/main/Websites/browserbench.org/JetStream2.0 |
| v2.1 |  https://github.com/WebKit/WebKit/tree/main/Websites/browserbench.org/JetStream2.1 |
| v2.2 |  https://github.com/WebKit/WebKit/tree/main/Websites/browserbench.org/JetStream2.2 |

**Comment by kmiller68** [comment]
I've created the following branches:

| Branch Name  | Source | 
| -- | -- |
| v1.1 | https://github.com/WebKit/JetStream/tree/JetStream1.1 | 
| v2.0 | https://github.com/WebKit/JetStream/tree/JetStream2.0 |
| v2.1 | https://github.com/WebKit/JetStream/tree/JetStream2.1 |
| v2.2 | https://github.com/WebKit/JetStream/tree/JetStream2.2 |

Let me know if anything is missing. If not, feel free to close this.
